server:
  port: 8080

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8
  username: root
  password: ok

mybatis:
  config-file: mybatis-config.xml
  mapper-path: /mapper/**.xml
  modelPackage: com.app.dao.demo.model
